name: alpine
on:
  push:
    branches:
      - "workflow"
  workflow_dispatch:
env:
  FORCE_COLOR: 1
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - 20
        target:
          - linux/arm/v7
          - linux/arm/v6
        variant:
          - alpine3.19
    name: ${{ matrix.variant }} (node=${{ matrix.node }}, target=${{ matrix.target }})
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build binaries and test
        run: |
          docker build \
            --file ./docker/Dockerfile \
            --load \
            --tag sqlite-builder \
            --no-cache \
            .
          CONTAINER_ID=$(docker create -it sqlite-builder)
          docker exec -it $CONTAINER_ID node -p "process.arch"
